language: java
jdk: openjdk8

before_install:
  - bash lib/download_libs.sh
  - bash maxmind/download_maxmind_geo_ip_db.sh

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

